cddrogue = 1  # Change this to alter the Cd of the drogue
adrogue = 0.4 # Change this to alter the area of the drogue
amain = 1.4 # Change this to alter the area of the main chute
cdmain = 2  # Change this to alter the area of the main chute
drogueheight = 100000  # Change this to alter the drogue deploy height
mainheight = 1000  # Change this to alter the main chute deploy height
droguedeploytime = 10  # Change this to alter the drogue deploy time
maindeploytime = 10  # Change this to alter the main chute deploy time
cddown = 0.4